on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest 

    steps: 
      - name: 'Before printing the folder containts'
        run: ls

      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username mego265 --password dckr_pat_XWqfnOLl-ywXuMGVPemXhLnv0Rs

