on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest 

    steps: 
      - name: 'Before printing the folder containts'
        run: ls

      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME}} --password ${{ secrets.DOCKER_TOOKEN }}
      
      - name: " building docker "
        run: docker build -t ${{ secrets.DOCKER_USERNAME}}/docker-image-creation .
      
      - name: " pushing to docker hub "
        run: docker push ${{ secrets.DOCKER_USERNAME}}/docker-image-creation

